name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Package app for macOS
        if: matrix.os == 'macos-latest'
        run: npm run make

      - name: Package app for Windows
        if: matrix.os == 'windows-latest'
        run: npm run make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/make/**/*.exe
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.AppImage
            out/make/**/*.snap
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
